version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR Repo..."
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264501343.dkr.ecr.us-east-1.amazonaws.com)
      - REPOSITORY_URI=058264501343.dkr.ecr.us-east-1.amazonaws.com/demo-flask-app
      - IMAGE_TAG=$(date +"%m%d%Y%H%M%S")
  build:
    commands:
      - echo "starting build on $(date)"
      - echo "Building the docker image"
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the docker image"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
